### ISSUE TITLE
Option to add a \0 at the end of the data

### ISSUE THREAD

**Issue by scippie75** [ckormanyos/xxd#53]
When creating a C header file with xxd from a file, it may sometimes be a piece of text you want to include.
It would be handy if it can be used directly as a c-string which would need to be zero terminated.
So an option to add a \0 at the end would be a nice to have feature.

**Comment by ckormanyos** [comment]
Hi @scippie75 thanks for your query. We can have this discussion. But be warned, I'm not really the best `xxd`developer, I acted merely as a scribe to make it standalone.

That notwithstanding, I'd be reluctant to implement features here that are not ordinarily in the supported `xxd`program.

If you could get it into the "real" xxd, then we could backport it here no problem. Otherwise, we would need to consider adding your requested feature as a special request and separate it from the ordinary release(s). I'm not sure how to handle this.

Do you know if the ordinary `xxd` has this feature?

We could also give you a fork and implement the feature in your specific fork.

**Comment by scippie75** [comment]
Ow sorry, I didn't know this wasn't the official xxd.
Do you know where the official one is so I can request the feature there?

**Comment by ckormanyos** [comment]
> where the official one is 

Yes, `xxd` is commonly distributed as a part of the [vim-project](https://www.vim.org).
